In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(1,5)

array([1, 2, 3, 4])

In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
np.ones(25)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2.])

In [20]:
np.arange(5,26) * 2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [24]:
np.random.rand(1)

array([0.50688617])

In [25]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [28]:
np.random.randn(25)

array([ 0.16512624,  0.25815903,  0.60588807,  0.80890444, -0.26761824,
       -0.45460921, -1.15530839, -1.17570199, -0.92052521,  0.86031266,
        0.84040159,  1.51606191, -0.91639283, -0.53290199, -0.43194876,
       -0.12534076, -0.93917853, -1.17330168,  2.22121609,  1.59511352,
       -0.34805484, -0.3949796 ,  0.37028162,  1.1051875 ,  1.07764447])

In [35]:
np.arange(1, 101).reshape(10,10) * 0.01

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [37]:
np.linspace(0,2,21)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [38]:
mat = np.arange(1,26).reshape(5,5)

In [42]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [50]:
mat[3:4,4:5]

array([[20]])

In [51]:
mat[3,4]

20

In [52]:
np.array([[2],[7],[12]])

array([[ 2],
       [ 7],
       [12]])

In [53]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [54]:
mat[4]

array([21, 22, 23, 24, 25])

In [57]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
mat.sum()

325

In [64]:
mat.std()

7.211102550927978

In [65]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

m

In [66]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])