In [1]:
import torch

In [17]:
x = torch.tensor(2.0,requires_grad=True)

In [18]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [19]:
y

tensor(63., grad_fn=<AddBackward0>)

In [20]:
type(y)

torch.Tensor

In [21]:
y.backward()

In [22]:
x.grad

tensor(93.)

In [23]:
y

tensor(63., grad_fn=<AddBackward0>)

In [24]:
x

tensor(2., requires_grad=True)

In [25]:
x.grad

tensor(93.)

In [27]:
type(y)

torch.Tensor

In [28]:
y

tensor(63., grad_fn=<AddBackward0>)

In [29]:
x = torch.tensor([[1.,2.,3.], [3.,2.,1.]], requires_grad=True)

In [30]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [31]:
y = 3*x + 2

In [32]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [33]:
z = 2*y**2

In [34]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [35]:
out = z.mean()

In [36]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [37]:
out.backward()

In [38]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
