In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'1.6.0'

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [11]:
x = torch.from_numpy(arr)

In [14]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [15]:
x.dtype

torch.int32

In [18]:
arr2d = np.arange(0.0,12.0)

In [20]:
arr2d = arr2d.reshape(4, 3)

In [21]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [25]:
x2 = torch.from_numpy(arr2d)

In [26]:
type(x2)

torch.Tensor

In [27]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [28]:
arr

array([1, 2, 3, 4, 5])

In [29]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [30]:
arr[0] = 99

In [31]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [32]:
my_arr = np.arange(0,10) 

In [33]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_tensor = torch.tensor(my_arr)

In [35]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [36]:
my_other_tensor = torch.from_numpy(my_arr)

In [37]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [38]:
my_arr[0] = 999

In [39]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [40]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [44]:
new_arr = np.array([1,2,3])

In [45]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [47]:
my_tensor = torch.Tensor(new_arr)

In [48]:
my_tensor.dtype

torch.float32