In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'1.6.0'

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [11]:
x = torch.from_numpy(arr)

In [14]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [15]:
x.dtype

torch.int32

In [18]:
arr2d = np.arange(0.0,12.0)

In [20]:
arr2d = arr2d.reshape(4, 3)

In [21]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [25]:
x2 = torch.from_numpy(arr2d)

In [26]:
type(x2)

torch.Tensor