In [1]:
import torch
import numpy as np

In [4]:
x = torch.arange(6).reshape(3,2)

In [5]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
x[1,1]

tensor(3)

In [7]:
x = torch.arange(10)

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])